baseURL: https://sage-granita-71ace4.netlify.app/
languageCode: en-us
title: My New Hugo Site
theme: paper

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10          